# quick demo script with nifi and kafka with a registry too

version: "3.7"
services:
    node:
        build:
            context: ../docker
            dockerfile: Dockerfile
        image: fakestream:latest
        volumes:
            - "../scripts:/opt/scripts"
            - "../scripts/generators:/opt/scripts/generators"
            - "../scripts/log:/opt/scripts/log"
        ports:
            - 8080:8080
    registry:
        image: apache/nifi-registry:latest
        ports:
            - 18080:18080
    spark-master:
        image: spark-master:latest
        ports:
        - "9090:8080"
        - "7077:7077"
        volumes:
        - ./spark-apps:/opt/spark-apps
        - ./spark-data:/opt/spark-data
        environment:
        - "SPARK_LOCAL_IP=spark-master"
    spark-worker:
        image: spark-worker:latest
        depends_on:
        - spark-master
        environment:
        - SPARK_MASTER=spark://spark-master:7077
        - SPARK_WORKER_CORES=4
        - SPARK_WORKER_MEMORY=6G
        - SPARK_DRIVER_MEMORY=128m
        - SPARK_EXECUTOR_MEMORY=256m
        volumes:
        - ./spark-apps:/opt/spark-apps
        - ./spark-data:/opt/spark-data
    notebook:
        #build: docker/
        image: datadrone/spark_notebook:latest
        ports:
        - "9200:8888"
        environment:
        - JUPYTER_ENABLE_LAB=yes
        - SPARK_OPTS='--master=spark://spark-master:7077'
        ipc: host
        volumes:
        - /home/brian/Workspace:/home/jovyan/work
        - ./spark-data:/opt/spark-data
    zookeeper:
        image: wurstmeister/zookeeper:3.4.6
    kafka:
        image: wurstmeister/kafka:2.12-2.2.1
        environment:
            KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
            KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
            KAFKA_CREATE_TOPICS: "input:1:1, output:1:1"
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        ports:
            - 9094:9094